[package]
name = "nightsong-bot"
version = "0.1.0"
authors = ["Valeryi Savich <relrin78@gmail.com>"]
edition = "2018"
description = "The Discord bot for managing server rooms"
readme = "README.md"

[dependencies]
chrono = "0.4.10"
failure = "0.1.6"
lazy_static = "1.4.0"
serde_json = "1.0.44"

[dependencies.diesel]
features = [
    "chrono",
    "postgres",
    "serde_json",
]
version = "1.4.3"

[dependencies.serenity]
default-features = true
version = "0.7.4"

[dependencies.serde]
features = ["derive"]
version = "1.0"