[package]
name = "nightsong-bot"
version = "0.1.0"
authors = ["Valeryi Savich <relrin78@gmail.com>"]
edition = "2018"
description = "The Discord bot for managing server rooms"
readme = "README.md"

[dependencies]
chrono = "0.4.10"
diesel = { version = "1.4.3", features = ["postgres", "chrono", "serde_json"] }
dotenv = "0.15.0"
failure = "0.1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.44"

[dependencies.serenity]
default-features = true
version = "0.7.4"