[package]
name = "nightsong-bot"
version = "0.1.0"
authors = ["Valeryi Savich <relrin78@gmail.com>"]
edition = "2018"
description = "The Discord bot for managing server rooms"
readme = "README.md"

[dependencies]
failure = "0.1.6"
lazy_static = "1.4.0"
regex = "1.3.1"
readonly = "0.1.5"

[dependencies.serenity]
default-features = true
version = "0.7.4"